@extends('layouts.app')
@section('title', 'Home Page')
@section('content')
@include('partials.home.hero')
@include('partials.home.feature')
@include('partials.home.about')
@include('partials.home.team')
@include('partials.home.service')
